version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on: 
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    container_name: mysql_my_first_app
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 33306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    
volumes: 
  db-volume: