# Generated by Django 3.0.4 on 2020-04-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Post',
        ),
    ]
